<?php
 class PermissionAuditType
{ public $value__;
public $ADD_GROUP_PERMISSION;
public $ADD_USER_GROUP;
public $ADD_USER_PERMISSION;
public $CREATE_GROUP;
public $CREATE_GROUP_LIST;
public $CREATE_USER;
public $CREATE_USER_LIST;
public $DELETE_GROUP;
public $DELETE_GROUP_LIST;
public $DELETE_GROUP_PERMISSION;
public $DELETE_USER_GROUP;
public $DELETE_USER;
public $DELETE_USER_LIST;
public $DELETE_USER_PERMISSION;
public $ENABLE_GROUP;
public $DISABLE_GROUP;
public $RENAME_GROUP;
public $SET_USER_EMAIL;
public $SET_SUPERADMIN;
public $UNSET_SUPERADMIN;
public $ADD_GROUP_LIST_ITEMS;
public $UPDATE_GROUP_LIST_ITEMS;
public $DELETE_GROUP_LIST_ITEMS;
public $ADD_USER_LIST_ITEMS;
public $UPDATE_USER_LIST_ITEMS;
public $DELETE_USER_LIST_ITEMS;
 
} 
?>