namespace LinnworksAPI
{
    public enum FilterNameType
    {
        General,
        SKU,
        Title,
        RetailPrice,
        PurchasePrice,
        Tracked,
        Barcode,
        VariationsGroupName,
        Available,
        MinimumLevel,
        InOrder,
        StockLevel,
        StockValue,
        Due,
        BinRack,
        Category,
        ChannelSKU,
        SupplierCode,
        eBayId,
        AmazonASIN,
        Image,
        ExtendedProperty,
        ExtendedPropertyName,
    }
}